# Generated by Django 5.2.4 on 2025-07-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
