# Generated by Django 5.2.4 on 2025-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
