# Generated by Django 5.2.4 on 2025-07-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
